#### Naive bayes classifier
1. Basic of Postier and Conditional probability
2. Introduction of NBC
2.1. Gaussion distribution
2.2. Multinomial
2.3. Bernoulli 
4. Bayes theorm and implementation of NBC and
5. Its applications

In [1]:
from pandas import*
from numpy import*
import numpy as np
import pandas as pd
import sklearn


from sklearn import datasets

In [2]:
wine = datasets.load_wine()

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [5]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [6]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [3]:
data = pd.DataFrame(wine['data'])
data.head(2)

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   

       12  
0  1065.0  
1  1050.0

In [8]:
data.shape

(178, 13)

#### Splt the data for Gaussion based NBC

In [12]:
Y = wine['target']

In [11]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain,xtest,ytrain,ytest = train_test_split(data,Y,test_size=0.25,random_state=2)

#### Fit the model

In [16]:
from sklearn.naive_bayes import GaussianNB

In [18]:
gnb = GaussianNB()
gnb.fit(xtrain,ytrain)

GaussianNB()

#### Prediction 

In [20]:
y_pred = gnb.predict(xtest)
print(y_pred)

[0 0 2 1 0 0 1 2 1 0 1 0 0 2 2 1 0 0 0 2 2 0 1 1 0 0 1 0 0 0 2 1 2 2 0 1 2
 1 1 1 2 2 1 0 2]


#### Accuracy 

In [21]:
from sklearn.metrics import confusion_matrix

In [23]:
cm  = confusion_matrix(ytest,y_pred)
cm ## Diagnol is the correct prediction

array([[18,  1,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

#### Implementation on Text Classification by Multinomial

In [4]:
from sklearn.datasets import fetch_20newsgroups

In [5]:
news = fetch_20newsgroups()

In [6]:
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [7]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [8]:
news_data = pd.DataFrame(news['data'])#usecols=['alt.atheism', 'soc.religion.christian','comp.graphics','sci.med'])
news_data.head(2)

0
0  From: lerxst@wam.umd.edu (where's my thing)\nS...
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...

In [12]:
cat = ['alt.atheism', 'soc.religion.christian','comp.graphics','sci.med']

In [46]:
categories

['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

#### train the model

#### from sklearn Count vectorizer()

it convert text to 0 or 1 values

this the first
this is the second
this is the third 
this is last one


here we need to find out the unique world

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

In [13]:
news_train =  fetch_20newsgroups(subset='train', categories=cat)

In [14]:
news_test = fetch_20newsgroups(subset='test', categories=cat)

In [16]:
xtrain = count_vect.fit_transform(news_train.data)

In [17]:
xtrain.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
xtrain.shape

(2257, 35788)

#### Tfidf 

In [19]:
from sklearn.feature_extraction.text import TfidfTransformer

In [20]:
tdf = TfidfTransformer()

In [21]:
xtraintdf = tdf.fit_transform(xtrain)

In [22]:
xtraintdf.shape #only provide the weightege

(2257, 35788)

In [23]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
model = MultinomialNB().fit(xtraintdf, news_train.target)

#### TEst the model

In [26]:
x_test_df = count_vect.transform(news_test.data)

In [27]:
x_test_t =  tdf.transform(x_test_df)  

#### Predict the model

In [29]:
pred = model.predict(x_test_t)
pred

array([2, 2, 3, ..., 2, 2, 1])

#### done