1. KNN and its Steps
2. Differnce btw Manhattan and Euclidean distance
3. K-fold Cross validation

In [2]:
import pandas as pd
import numpy as np
from sklearn import*

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
df = pd.DataFrame(iris['data'])
print(df.head())

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2


In [6]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [7]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

#### Split the data

In [35]:
x = df
y = iris['target']

In [36]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=0)

#### Creating a algorithm

In [37]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

#### Train the model

In [38]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

#### Prediction 

In [43]:
new = np.array([[5,2,3,0.2]]) # in our dataset we have four feature so we put here 4 values

In [44]:
prediction = knn.predict(new)
prediction

array([1])

In [45]:
iris['target_names'][prediction]

array(['versicolor'], dtype='<U10')

#### Confusion matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [50]:
y_pred = knn.predict(xtest)

cm = confusion_matrix(ytest,y_pred)
print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


#### Accuracy

In [51]:
print(accuracy_score(ytest,y_pred))

0.9736842105263158


#### K - fold Cross Validation

In [52]:
x = iris.data
y = iris.target

In [53]:
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [ ]:
#### LOgictic Reg

In [55]:
LS_Score = cross_val_predict(LogisticRegression(),x,y)

/home/m/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [56]:
np.average(LS_Score)

1.0133333333333334

#### Decision tree

In [59]:
dt_score = cross_val_predict(DecisionTreeClassifier(),x,y)

In [58]:
np.average(dt_score)

0.9933333333333333

#### SVM

In [61]:
svm_score = cross_val_predict(SVC(),x,y)

In [62]:
np.average(svm_score)

0.9933333333333333

#### K-fold another mehtod

In [63]:
from sklearn.model_selection import KFold

In [65]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

#### Web Scraping

1. why 
2. what

#### steps:

1. find the urls
2. inspecting the page
3.   find the dataset and extraxt
4. code
5. execute
6. store the data
#### Libraries:
1. Selenium
2. Beautiful Soup
3. Pandas
4. Scrapy